apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hiveMetastore.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
    app.kubernetes.io/component: metastore
    {{- include "hiveMetastore.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
      app.kubernetes.io/component: metastore
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  serviceName: {{ include "hiveMetastore.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
        app.kubernetes.io/component: metastore
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: metastore
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: DATABASE_HOST
          value: "{{ .Release.Name }}-postgresql"
        - name: DATABASE_DB
          value: "{{- .Values.postgresql.global.postgresql.auth.database }}"
        - name: DATABASE_USER
          value: "{{- .Values.postgresql.global.postgresql.auth.username }}"
        - name: DATABASE_PASSWORD
          value: "{{- .Values.postgresql.global.postgresql.auth.password }}"
        command:
        - "/bin/sh"
        - "-c"
        - "/opt/hive-metastore/bin/start-metastore"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: hive-config
          mountPath: /opt/hive-metastore/conf
        - name: warehouse-dir
          mountPath: /opt/hive-metastore/warehouse
      volumes:
      - name: hive-config
        configMap:
          name: {{ include "hiveMetastore.fullname" . }}
      - name: warehouse-dir
        emptyDir: {}
        

